kind: pipeline
type: docker
name: default

steps:
- name: build_packages
  failure: ignore
  image: phillipkhne/trizen-docker
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
    - mkdir -p ./pkgs
    - trizen -Sy --noinstall --noconfirm ttf-ms-fonts

# For ssh copy
#- name: deploy_packages
#  image: ictu/sshpass
#  commands:
#    - sshpass -p "uses_sftp" rsync -lrvh -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" pkgs/ sftpuser@192.168.2.101:html/archpkgs/

- name: deploy_packages
  image: ictu/sshpass
  commands:
    - rsync -lrvh --no-compress pkgs/ /var/outdir
  volumes:
    - name: outdir
      path: /var/outdir


- name: create_repo
  image: phillipkhne/trizen-docker
  volumes:
  - name: outdir
    path: /var/outdir
  commands:
    - sudo repo-add /var/outdir/phillip-private.db.tar.zst /var/outdir/*.pkg.tar.*

volumes:
  - name: outdir
    host:
        path: /var/www/html/archpkgs/

---

kind: pipeline
type: docker
name: test

steps:
- name: echo
  failure: ignore
  image: phillipkhne/trizen-docker
  commands:
    - ls -al .
    - whoami
    - cat /etc/makepkg.conf