kind: pipeline
type: docker
name: default

steps:
- name: rsync_existing
  image: ictu/sshpass
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
   - sshpass -p "${PASSWORD}" rsync -lrvzh -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ${USERNAME}@192.168.2.101:html/archpkgs/ pkgs/

- name: build_packages
  image: phillipkhne/trizen-docker
  environment:
    PACKAGES:
      from_secret: packages
  commands:
    - sudo mkdir -p ./pkgs
    - trizen -Sy --noinstall --noconfirm --movepkg-dir=./pkgs ${PACKAGES}

- name: create_repo
  image: phillipkhne/trizen-docker
  commands:
    - sudo repo-add ./pkgs/phillip-private.db.tar.xz ./pkgs/*.pkg.tar.*

- name: deploy_packages
  image: ictu/sshpass
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - sshpass -p "${PASSWORD}" rsync -lrvzh -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" pkgs/ ${USERNAME}@192.168.2.101:html/archpkgs/
