kind: pipeline
type: docker
name: default

steps:
- name: test
  image: phillipkhne/trizen-docker
  commands:
    - sudo mkdir ./pkgs
    - trizen -Sy --noinstall --noconfirm --movepkg-dir=./pkgs ttf-symbola

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 192.168.2.101
    username: sftpuser
    password: uses_sftp
    port: 22
    source: pkgs/*.pkg.tar.xz
    target: /var/www/html/archpkgs/
    rm: true