kind: pipeline
type: docker
name: default

steps:
- name: test
  image: phillipkhne/trizen-docker
  commands:
    - sudo mkdir ./pkgs
    - trizen -Sy --noinstall --noconfirm --movepkg-dir=./pkgs ttf-symbola
    - sshpass -p "uses_sftp" scp pkgs/*.pkg.tar.xz sftpuser@192.168.2.101:html/archpkgs/

- name: deploy
  image: ictu/sshpass
  commands:
    - sshpass -p "uses_sftp" scp pkgs/*.pkg.tar.xz sftpuser@192.168.2.101:html/archpkgs/
