kind: pipeline
type: docker
name: default

steps:
- name: rsync_existing
  image: ictu/sshpass
  commands:
   - sshpass -p "uses_sftp" rsync -lrvzh -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" sftpuser@192.168.2.101:html/archpkgs/ pkgs/

- name: build_packages
  image: phillipkhne/trizen-docker
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
    - sudo mkdir -p ./pkgs
    - trizen -Sy --noinstall --noconfirm --movepkg-dir=./pkgs doomseeker zandronum intellij-idea-ultimate-edition intellij-idea-ultimate-edition-jre pycharm-professional

- name: create_repo
  image: phillipkhne/trizen-docker
  commands:
    - sudo repo-add ./pkgs/phillip-private.db.tar.xz ./pkgs/*.pkg.tar.*

- name: deploy_packages
  image: ictu/sshpass
  commands:
    - sshpass -p "uses_sftp" rsync -lrvzh -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" pkgs/ sftpuser@192.168.2.101:html/archpkgs/
