kind: pipeline
type: docker
name: default

steps:
- name: test
  image: phillipkhne/trizen-docker
  commands:
    - trizen -Sy --noinstall --noconfirm --movepkg platformio

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: phillipathome.dynv6.net
    username: sftpuser
    password: uses_sftp
    port: 22
    target: /var/www/html/archpkgs/
    source: /var/cache/pacman/pkg/*